//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 05:02:43 ŒßŒã JST 
//


package jp.ac.nagoyau.is.ss.kishii.ob.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jp.ac.nagoyau.is.ss.kishii.ob.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Team_QNAME = new QName("http://www.example.org/1.0", "team");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jp.ac.nagoyau.is.ss.kishii.ob.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Team }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/1.0", name = "team")
    public JAXBElement<Team> createTeam(Team value) {
        return new JAXBElement<Team>(_Team_QNAME, Team.class, null, value);
    }

}
