//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 05:02:43 ŒßŒã JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jp.ac.nagoyau.is.ss.kishii.ob.xml;
